### ISSUE TITLE
Cant Install on Ubuntu 20.04

### ISSUE THREAD

**Issue by xmaxmex** [richbl/go-distributed-motion-s3#19] opened 2022-04-23 00:35 UTC
Using golang 1.16 and 1.17.3

See the logs

xmaxmex@ubuntu:~/go-distributed-motion-s3$ ls
cmd     dms3build   dms3dashboard  dms3mail      dms3server  go.sum      LICENSE    ROADMAP.md
config  dms3client  dms3libs       dms3_release  go.mod      INSTALL.md  README.md
xmaxmex@ubuntu:~/go-distributed-motion-s3$ /usr/local/go/bin/go run cmd/compile_dms3/compile_dms3.go
Creating release folder for linux_arm8 platform...
Creating release folder for linux_amd64 platform...
Creating release folder for linux_arm6 platform...
Creating release folder for linux_arm7 platform...
Creating release folder for dms3client component...
Creating release folder for dms3server component...
Creating release folder for dms3mail component...
Creating release folder for install_dms3 component...
Creating release folder for dms3client_remote_installer component...
Creating release folder for dms3server_remote_installer component...
Creating release folder for dms3libs component...
Creating release folder for dms3dashboard component...
Building dms3 components for linux_arm6 platform...
exit status 1
exit status 1
xmaxmex@ubuntu:~/go-distributed-motion-s3$

Any idea?

**Comment by richbl** [comment] 2022-04-23 16:08
@xmaxmex , thanks for flagging this issue.

The build process is a separate process from the rest of the dms3 executables, and relies on your local machine environment configuration. While I was unable to reproduce the issue that you had (running golang 1.17.7), I can provide you with some debugging actions that may help resolve the issue.

The build process happens in func `BuildComponents()` (file `lib_build.go` in `/dms3build`). You'll see that this function iterates on the `BuildEnv` map variable. Confirm the proper configuration of `BuildEnv` variable (no changes should be required). Since the process exits on the compilation of individual platforms, I suspect that your local machine configuration may not support them all. These include (by default):

	linuxArm6  platformType = "linuxArm6"
	linuxArm7  platformType = "linuxArm7"
	linuxArm8  platformType = "linuxArm8"
	linuxAMD64 platformType = "linuxAMD64"
	
The respective compiler tags are as follows:

	compileTags: "GOOS=linux GOARCH=arm GOARM=6"
	compileTags: "GOOS=linux GOARCH=arm GOARM=7"
	compileTags: "GOOS=linux GOARCH=arm64"
	compileTags: "GOOS=linux GOARCH=amd64"
	
So, to test your that your local machine environment can build these different executables, I'd recommend that you build each by hand, on command line, to confirm that each will platform executable will build correctly. In short, we're going to do what  `BuildComponents()` does programmatically.

For example, to build the ARM6 version of `dms3client`, you'd run the following command:

	env GOOS=linux GOARCH=arm GOARM=6 go build -o dms3_release/cmd/linux_arm6/dms3client cmd/dms3client/dms3client.go

> Note that the output location (dms3_release) is created as part of the build process, so feel free to save the output file (the -o flag) to another existing location.

I'd suggest you iterate over all of the platform types to identify the failing environment configuration. This will be helpful in identifying dependencies.

I'd suspect that the failure you're experiencing has something to do with the local machine build environment (possibly the golang environment). If this is indeed the case, it's possible that there is a local build environment requirement that has not yet been documented.

Good luck with your investigation.

Rich

**Comment by richbl** [comment] 2022-06-02 22:44
No follow-up response from OP, so closing out this ticket.

**Closed by richbl** 2022-06-02 22:44 UTC
